# It contains all the configs required in the project

artifacts: 
  base_data: artifacts/data_df.pickle
  callbacks_log: artifacts/logs/fit
  artifacts_dir: artifacts
  model_config_dir: artifacts/model_ckpt.h5
  config_path: configs/config.yaml

source_data_dirs:
  data: data/Churn_Modelling.csv


params:
  test_size: 0.15
  random_state: 22
  TEST_BATCH_SIZE: 1000
  activation_1: relu
  activation_2: sigmoid
  Losses: binary_crossentropy
  Metrics: accuracy
  Optimizer: adam
  patience: 25
  EPOCHS: 200
